# server.port=${PORT:8080}

# spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:ecuavoley_db}

# spring.datasource.username=${PGUSER:postgres}

# spring.datasource.password=${PGPASSWORD}

# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.jpa.show-sql=false

# spring.jpa.properties.hibernate.format_sql=false


# # ==========================================
# # ADMIN
# # ==========================================

# ecuavoley.admin.code=${ADMIN_CODE}




spring.application.name=ecuavoley-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ecuavoley_db
spring.datasource.username=postgres
spring.datasource.password=6128

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

ecuavoley.admin.code=${ECUAVOLEY_ADMIN_CODE:1234}